### ISSUE TITLE
how to build libASRLocalSDK.a

### ISSUE THREAD

**Issue by HuangChaoChao** [andyweiqiu/asr-ios-local#6]
hello,I follow your work.I want to know how to build libASRLocalSDK.a

**Comment by andyweiqiu** [comment]
> hello,I follow your work.I want to know how to build libASRLocalSDK.a

You first have to know how to build a static library on xcode, and then package your own logic as ‘.a’

**Comment by Hanwun** [comment]
@andyweiqiu
感谢这阵子的协助！

对于静态档怎么编译很有兴趣，
目前已编译过android kaldi library
可以和你请教如何build on ios的kaldi 相关静态档案？
或者我们透过邮件讨论

再麻烦您了
Email: hwlien0809@gmail.com

谢谢！

**Comment by Hanwun** [comment]
@andyweiqiu 
Hi,
参考网路kaldi ios相关资料，
目前我已经build kaldi library.a, openfst.a, openblas.a ，
对于放入专案里面是单纯把.a档置换即可，还是其相关.h也需要一并让入?

另外想请问您的libASRLocalSDK.a是与什么library相关呢?

麻烦您了。
谢谢!

**Comment by andyweiqiu** [comment]
> @andyweiqiu
> Hi,
> 参考网路kaldi ios相关资料，
> 目前我已经build kaldi library.a, openfst.a, openblas.a ，
> 对于放入专案里面是单纯把.a档置换即可，还是其相关.h也需要一并让入?
> 
> 另外想请问您的libASRLocalSDK.a是与什么library相关呢?
> 
> 麻烦您了。
> 谢谢!

相关的.h肯定是要替换的，libASRLocalSDK.a主要包含audio流传输，解码过程，主要调用kaldi的东西。

**Comment by Hanwun** [comment]
@andyweiqiu 
可以请教如何编译audio流传输，解码过程，
是否有一些网上的.cc可以参考，
好像找不太到相关资料?

麻烦您了!

**Comment by andyweiqiu** [comment]
> @andyweiqiu
> 可以请教如何编译audio流传输，解码过程，
> 是否有一些网上的.cc可以参考，
> 好像找不太到相关资料?
> 
> 麻烦您了!

网上是否有参考的我也不太清楚，我这边都是自己写，audio传输部分其实就是一个管控流的机制，一端收流，一端获取流解码，网上有个开源的工具GStreamer，但是库有点大，就自己写了。解码主要是调用kaldi的解码部分。

**Comment by Hanwun** [comment]
可否发一份您撰写的编译脚本及编译过程，
Email: hwlien0809@gmail.com
目前仅能编译libkaldi-ios.a, libfst-ios.a, libopenblas-armv8p-0.2.20.a,
想说可否结合您的编译脚本合成libASRLocalSDK.a?

**Comment by andyweiqiu** [comment]
> 可否发一份您撰写的编译脚本及编译过程，
> Email: [hwlien0809@gmail.com](mailto:hwlien0809@gmail.com)
> 目前仅能编译libkaldi-ios.a, libfst-ios.a, libopenblas-armv8p-0.2.20.a,
> 想说可否结合您的编译脚本合成libASRLocalSDK.a?

没有编译脚本，只是普通的编译iOS静态库，在xcode上就可以。

**Comment by Hanwun** [comment]
Hi @andyweiqiu 

想请问您知道如何build eanble bitcode的static library (openfst, kaldi/src)，
目前你提供的好像是把Enabled bitcode关掉了。

想了解如果要将Enabled bitcode改设定为yes，
那在Build library需要做什么修改或参数设定呢?

麻烦您了!
谢谢

**Comment by andyweiqiu** [comment]
> Hi @andyweiqiu
> 
> 想请问您知道如何build eanble bitcode的static library (openfst, kaldi/src)，
> 目前你提供的好像是把Enabled bitcode关掉了。
> 
> 想了解如果要将Enabled bitcode改设定为yes，
> 那在Build library需要做什么修改或参数设定呢?
> 
> 麻烦您了!
> 谢谢

你可以在编译的时候加上-fembed-bitcode试试，我有时间编个支持bitcode的版本
