### ISSUE TITLE
数学计算库

### ISSUE THREAD

**Issue by xuducan** [andyweiqiu/asr-ios-local#8]
您好，请问一下，您用的数学计算库是什么呢？能发一份您编译的库和kaldi相关编译的脚本给我吗？我的邮箱是ducanxu@163.com。谢谢！！

**Comment by andyweiqiu** [comment]
> 您好，请问一下，您用的数学计算库是什么呢？能发一份您编译的库和kaldi相关编译的脚本给我吗？我的邮箱是[ducanxu@163.com](mailto:ducanxu@163.com)。谢谢！！

库和编译脚本已发到你的邮箱。

**Comment by xuducan** [comment]
谢谢大佬！！
