### ISSUE TITLE
关于ARM Linux版本

### ISSUE THREAD

**Issue by JSnobody** [andyweiqiu/asr-ios-local#9]
您好，请问有ARM Linux的版本吗？
谢谢！

**Comment by andyweiqiu** [comment]
> 您好，请问有ARM Linux的版本吗？
> 谢谢！

你是想做嵌入式吗

**Comment by JSnobody** [comment]
> > 您好，请问有ARM Linux的版本吗？
> > 谢谢！
> 
> 你是想做嵌入式吗

是的啊
